name: example
description: A sample command-line application.
version: 1.0.0
publish_to: none

environment:
  sdk: '>=2.19.0-edge.efb509c114dcaf54d0a011f717b48893d71ec9c3 <3.0.0'

dependencies:
  dio: ^4.0.6
  http: ^0.13.5
  sse_stream:
    path: '..'

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
