name: sse_stream
description: Simple packages that converts text stream to sse events
version: 1.0.0
repository: https://github.com/zhalkhas/sse_stream
environment:
  sdk: '>=2.14.0 <4.0.0'
dev_dependencies:
  lints: ^2.0.1

